In [2]:
import tensorflow as tf

In [3]:
y = tf.constant([0,1,2,3]) # 数字编码的4个样本标签 
y = tf.one_hot(y, depth=10) # one-hot编码，指定类别总数为10 
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [4]:
a = tf.constant(1.0,dtype=tf.float16)

In [5]:
print('before:',a.dtype)  # 读取原有张量的数值精度 
if a.dtype != tf.float32:  # 如果精度不符合要求，则进行转换 
    a = tf.cast(a,tf.float32)  # tf.cast函数可以完成精度转换  
print('after :',a.dtype)  # 打印转换后的精度 

before: <dtype: 'float16'>
after : <dtype: 'float32'>


In [8]:
import numpy as np

In [9]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))  # 从数组中创建张量 

<tf.Tensor: id=7, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [10]:
a = tf.ones([2,3])  # 创建一个矩阵 
tf.zeros_like(a)  # 创建一个与a形状相同，但是全0的新矩阵 

<tf.Tensor: id=11, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [11]:
tf.fill([], -1)  # 创建-1的标量 

<tf.Tensor: id=14, shape=(), dtype=int32, numpy=-1>

In [12]:
tf.fill([1], -1)

<tf.Tensor: id=17, shape=(1,), dtype=int32, numpy=array([-1])>

In [14]:
tf.random.normal([2,2], mean=1,stddev=2)  # 创建正态分布的张量 

<tf.Tensor: id=29, shape=(2, 2), dtype=float32, numpy=
array([[ 3.135792  ,  2.869121  ],
       [-0.10262239,  0.8181862 ]], dtype=float32)>

In [15]:
tf.random.uniform([2,2])  # 创建采样自[0,1)均匀分布的矩阵 

<tf.Tensor: id=36, shape=(2, 2), dtype=float32, numpy=
array([[0.61551845, 0.06665766],
       [0.82344055, 0.27597034]], dtype=float32)>

In [16]:
tf.range(1,10,delta=2)  # 1~10 

<tf.Tensor: id=40, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [18]:
fc = tf.keras.layers.Dense(3) # 创建一层Wx+b，输出节点为3 
# 通过build函数创建W,b张量，输入节点为4 
fc.build(input_shape=(2,4))  
fc.bias # 查看偏置向量

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [19]:
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.06134337,  0.38081586, -0.09358341],
       [ 0.50312555,  0.88170314, -0.880754  ],
       [ 0.5763267 ,  0.1001147 , -0.03915447],
       [-0.89779013, -0.33215195, -0.41262072]], dtype=float32)>

In [29]:
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)

In [30]:
x = tf.expand_dims(x,axis=2)  # axis=2表示宽维度后面的一个维度 
x

<tf.Tensor: id=115, shape=(28, 28, 1), dtype=int32, numpy=
array([[[6],
        [4],
        [9],
        [6],
        [1],
        [8],
        [5],
        [0],
        [5],
        [2],
        [6],
        [4],
        [0],
        [5],
        [2],
        [1],
        [8],
        [5],
        [1],
        [1],
        [3],
        [7],
        [5],
        [8],
        [4],
        [0],
        [2],
        [5]],

       [[0],
        [7],
        [4],
        [9],
        [1],
        [6],
        [5],
        [6],
        [9],
        [4],
        [1],
        [1],
        [8],
        [8],
        [8],
        [9],
        [7],
        [8],
        [9],
        [4],
        [0],
        [5],
        [4],
        [6],
        [2],
        [8],
        [3],
        [1]],

       [[4],
        [2],
        [0],
        [3],
        [3],
        [9],
        [9],
        [2],
        [8],
        [5],
        [5],
        [9],
        [9],
        [7],
        [5],
        [8],
 

In [32]:
x = tf.squeeze(x, axis=2)
x

<tf.Tensor: id=116, shape=(28, 28), dtype=int32, numpy=
array([[6, 4, 9, 6, 1, 8, 5, 0, 5, 2, 6, 4, 0, 5, 2, 1, 8, 5, 1, 1, 3, 7,
        5, 8, 4, 0, 2, 5],
       [0, 7, 4, 9, 1, 6, 5, 6, 9, 4, 1, 1, 8, 8, 8, 9, 7, 8, 9, 4, 0, 5,
        4, 6, 2, 8, 3, 1],
       [4, 2, 0, 3, 3, 9, 9, 2, 8, 5, 5, 9, 9, 7, 5, 8, 9, 6, 9, 7, 5, 5,
        7, 9, 3, 0, 1, 0],
       [2, 8, 5, 3, 6, 8, 0, 1, 0, 1, 2, 5, 4, 6, 6, 1, 5, 8, 1, 0, 2, 4,
        7, 1, 8, 4, 3, 7],
       [4, 3, 8, 2, 5, 5, 1, 9, 1, 5, 7, 6, 8, 4, 7, 8, 5, 9, 6, 7, 4, 0,
        7, 1, 9, 1, 9, 8],
       [9, 8, 3, 5, 7, 9, 1, 4, 4, 5, 0, 2, 0, 7, 7, 1, 8, 0, 6, 9, 8, 5,
        4, 4, 9, 3, 2, 6],
       [7, 5, 2, 3, 3, 2, 6, 0, 0, 3, 7, 2, 2, 9, 8, 7, 1, 7, 0, 7, 8, 6,
        3, 1, 8, 0, 3, 6],
       [1, 6, 3, 6, 5, 2, 6, 6, 7, 2, 1, 9, 1, 4, 8, 0, 3, 2, 5, 7, 4, 5,
        2, 4, 6, 9, 8, 4],
       [3, 7, 0, 4, 3, 2, 9, 3, 9, 6, 0, 4, 0, 1, 1, 4, 6, 9, 0, 6, 2, 1,
        3, 0, 8, 4, 9, 1],
       [1, 9, 3, 4, 0, 0, 8, 9, 7, 

In [33]:
x = tf.random.normal([2,32,32,3]) 
tf.transpose(x,perm=[0,3,1,2])  # 交换维度 

<tf.Tensor: id=124, shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 0.415382  ,  0.24631141, -2.8748546 , ..., -1.1876612 ,
           0.08211755, -0.7094268 ],
         [ 0.14492574, -2.1187637 ,  1.1708531 , ..., -0.9561049 ,
           0.14909336,  2.068443  ],
         [-0.79923934,  1.1601065 ,  0.48161644, ..., -1.7396938 ,
          -0.45026106,  0.1086759 ],
         ...,
         [-0.7519923 , -0.4311949 ,  1.2089913 , ..., -0.06338049,
          -0.3498141 , -0.7219693 ],
         [ 0.89109445,  1.1188082 , -0.6766164 , ...,  1.0015007 ,
          -1.098376  , -0.08108067],
         [-0.77748436,  1.0918607 ,  0.8866936 , ...,  0.15265119,
           1.1068952 ,  2.0212033 ]],

        [[ 0.95647997,  0.7413287 , -0.4683624 , ...,  0.2034622 ,
          -0.08756426, -0.7313251 ],
         [-0.16787949,  0.09315364, -0.38815886, ...,  0.9009143 ,
          -1.0964457 ,  1.4342464 ],
         [-0.06170255,  0.7025782 , -1.3970193 , ...,  0.11383601,
           1.0374341 

In [34]:
# 合并是指将多个张量在某个维度上合并为一个张量。以某学校班级成绩册数据为例，
# 设张量㼿保存了某学校1~4号班级的成绩册，每个班级35个学生，共8门科目成绩，则张
# 量㼿的shape为：[4,35,8]；同样的方式，张量㼿保存了其它6个班级的成绩册，shape为
# [6,35,8]。通过合并这2份成绩册，便可得到学校所有班级的成绩册，记为张量㼿，shape应
# 为[10,35,8]，

a = tf.random.normal([4,35,8]) # 模拟成绩册A 
b = tf.random.normal([6,35,8]) # 模拟成绩册B 
tf.concat([a,b],axis=0) # 拼接合并成绩册 

<tf.Tensor: id=138, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-0.9025693 , -0.57737243,  1.1063505 , ...,  0.1297835 ,
          0.41969305,  0.12174791],
        [ 0.75844926,  1.6602179 , -0.461109  , ...,  1.4546267 ,
         -0.8092456 ,  0.9124249 ],
        [ 1.2544005 ,  1.2855452 ,  0.7100562 , ...,  2.1484363 ,
         -0.9466857 , -0.29199535],
        ...,
        [-1.7284358 , -0.53867584,  0.16530675, ...,  0.4554064 ,
          2.295411  , -0.36055636],
        [-1.9316864 ,  0.66831934,  1.4353133 , ...,  1.630679  ,
         -0.28196472,  1.2127669 ],
        [ 0.6896193 , -2.783943  , -0.963298  , ..., -1.0220357 ,
          0.44582748, -0.516899  ]],

       [[ 0.71998906, -0.43703914,  0.6390902 , ...,  0.04173064,
          0.09596348,  0.04084536],
        [-0.4627468 ,  0.31736073,  1.1678501 , ...,  1.1252737 ,
          1.1504087 ,  1.4748527 ],
        [-1.1603082 , -0.42261022,  0.20724733, ..., -0.11169496,
          1.1810739 ,  0.73021066],
      

In [35]:
a = tf.random.normal([10,35,4]) 
b = tf.random.normal([10,35,4]) 
tf.concat([a,b],axis=2) # 在科目维度上拼接

<tf.Tensor: id=152, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-4.6282256e-01,  2.2994153e-02,  4.1513929e-01, ...,
         -1.0257075e+00, -5.7790335e-02, -3.1724897e-01],
        [-1.8743638e+00, -5.2187103e-01,  1.1405338e+00, ...,
         -5.5955082e-01, -8.5172033e-01, -1.6805660e-03],
        [-8.5433155e-01, -3.4195396e-01,  3.8486157e-02, ...,
         -8.3533496e-01,  1.4694813e-01, -6.2132537e-01],
        ...,
        [-9.3114698e-01, -3.8348202e-02, -4.9451664e-01, ...,
         -2.7651617e-01, -1.1178042e+00,  5.7528144e-01],
        [ 9.5561850e-01,  1.6150086e+00,  4.3880615e-02, ...,
          1.7320092e+00, -4.5649707e-01,  7.3639911e-01],
        [-1.2251039e+00,  3.3008134e-01, -4.3913582e-01, ...,
          1.2420807e+00,  3.1975129e-01, -9.3851614e-01]],

       [[ 9.6782583e-01,  5.1292222e-02, -1.1875659e+00, ...,
         -7.9586375e-01,  4.3299833e-01,  1.2893479e+00],
        [ 1.2292224e+00, -5.7820141e-01, -1.1053847e+00, ...,
         -6.9194001e-0

In [36]:
a = tf.random.normal([35,8]) 
b = tf.random.normal([35,8]) 
tf.stack([a,b],axis=0) # 堆叠合并为2个班级，班级维度插入在最前

<tf.Tensor: id=165, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-1.81532487e-01, -8.75882864e-01, -1.25637197e+00,
         -3.83489549e-01,  1.80650949e-01,  4.52502549e-01,
         -2.16300786e-01, -9.95381713e-01],
        [ 1.48994458e+00, -1.64057827e+00,  8.10533166e-01,
          2.92384446e-01, -1.98962763e-02, -4.85540420e-01,
         -1.48288846e+00, -2.08196950e+00],
        [-8.96768570e-01,  3.02771658e-01,  7.57590294e-01,
         -2.53648847e-01, -1.97308004e-01,  1.74501109e+00,
          1.09649312e+00, -4.96683180e-01],
        [-3.56530046e+00, -5.78333199e-01,  2.40823722e+00,
          3.33939576e+00, -1.15732718e+00, -8.32394183e-01,
          6.37846708e-01, -8.01572561e-01],
        [-5.99717498e-01, -9.43713844e-01,  7.27890909e-01,
          2.34333023e-01, -1.68214238e+00,  6.79294169e-01,
          5.00895977e-01, -1.72600257e+00],
        [-1.40973163e+00, -6.25890613e-01,  6.67549312e-01,
          7.02622771e-01,  1.33712545e-01, -7.95444012e-01,


In [37]:
tf.stack([a,b],axis=-1) # 在末尾插入班级维度 

<tf.Tensor: id=166, shape=(35, 8, 2), dtype=float32, numpy=
array([[[-1.81532487e-01,  1.27186346e+00],
        [-8.75882864e-01, -5.19610882e-01],
        [-1.25637197e+00, -5.50790429e-01],
        [-3.83489549e-01, -1.37501526e+00],
        [ 1.80650949e-01,  1.51581156e+00],
        [ 4.52502549e-01, -2.93188304e-01],
        [-2.16300786e-01, -7.52625823e-01],
        [-9.95381713e-01,  9.77223933e-01]],

       [[ 1.48994458e+00,  7.28642121e-02],
        [-1.64057827e+00, -1.49779272e+00],
        [ 8.10533166e-01, -5.92753112e-01],
        [ 2.92384446e-01,  1.90111709e+00],
        [-1.98962763e-02, -5.91444254e-01],
        [-4.85540420e-01, -1.52667865e-01],
        [-1.48288846e+00,  6.30514801e-01],
        [-2.08196950e+00,  8.90530109e-01]],

       [[-8.96768570e-01, -6.85331047e-01],
        [ 3.02771658e-01, -2.21042499e-01],
        [ 7.57590294e-01,  4.30664152e-01],
        [-2.53648847e-01, -7.51725078e-01],
        [-1.97308004e-01, -4.35932755e-01],
        [ 1.

In [38]:
x = tf.random.normal([10,35,8]) 
# 等长切割为10份 
result = tf.split(x, num_or_size_splits=10, axis=0) 
len(result)  # 返回的列表为10个张量的列表

10

In [42]:
x = tf.ones([2,2]) 
tf.norm(x,ord=1) # 计算L1范数 

<tf.Tensor: id=191, shape=(), dtype=float32, numpy=4.0>

In [43]:
tf.norm(x,ord=np.inf) # 计算∞范数

<tf.Tensor: id=195, shape=(), dtype=float32, numpy=1.0>

In [45]:
out = tf.random.normal([4,10]) # 模拟网络预测输出 
y = tf.constant([1,2,2,0]) # 模拟真实标签 
y = tf.one_hot(y,depth=10) # one-hot编码 
loss = tf.keras.losses.mse(y,out) # 计算每个样本的误差 
loss = tf.reduce_mean(loss) # 平均误差，在样本数维度上取均值 
loss # 误差标量

<tf.Tensor: id=222, shape=(), dtype=float32, numpy=1.3981448>

In [46]:
out = tf.random.normal([2,10]) 
out = tf.nn.softmax(out, axis=1) # 通过softmax函数转换为概率值 
out

<tf.Tensor: id=229, shape=(2, 10), dtype=float32, numpy=
array([[0.41190955, 0.03794109, 0.01228651, 0.01228719, 0.17189123,
        0.01121088, 0.15702686, 0.0704007 , 0.05748121, 0.05756476],
       [0.10255664, 0.02730231, 0.07823861, 0.06082024, 0.52068794,
        0.02778575, 0.07310976, 0.08847713, 0.00876891, 0.0122526 ]],
      dtype=float32)>

In [47]:
pred = tf.argmax(out, axis=1) # 选取概率最大的位置 
pred

<tf.Tensor: id=231, shape=(2,), dtype=int64, numpy=array([0, 4], dtype=int64)>

In [48]:
a = tf.constant([1,2,3,4,5,6]) # 第一个句子 
b = tf.constant([7,8,1,6]) # 第二个句子 
b = tf.pad(b, [[0,2]]) # 句子末尾填充2个0 
b # 填充后的结果 

<tf.Tensor: id=235, shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [49]:
x = tf.range(9) 
tf.clip_by_value(x,2,7) # 限幅为2~7 

<tf.Tensor: id=243, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7])>

In [50]:
x = tf.random.uniform([4,35,8],maxval=100,dtype=tf.int32) # 成绩册张量

In [51]:
# 收集第1,4,9,12,13,27号同学成绩 
tf.gather(x,[0,3,8,11,12,26],axis=1)  

<tf.Tensor: id=250, shape=(4, 6, 8), dtype=int32, numpy=
array([[[39, 41, 78, 29, 67, 67, 85, 36],
        [57, 83, 49, 67, 42, 36, 29, 98],
        [99, 73, 91, 40, 65, 49,  5, 70],
        [16, 91, 13, 75, 73, 65, 90, 24],
        [41, 88, 88, 97, 31, 26,  5, 93],
        [63, 66,  0, 99, 32, 60, 94, 80]],

       [[43, 29, 33, 43, 54,  0, 51, 29],
        [17, 20, 78, 24, 73, 53, 77, 46],
        [53, 57, 40, 84, 39, 47, 57, 46],
        [30, 25, 79, 76, 39, 57, 25, 90],
        [39, 91, 27, 27, 27, 10,  8,  9],
        [97, 83, 77, 29, 63, 74,  7, 28]],

       [[30, 75, 27, 73, 41, 99, 16,  9],
        [52, 84, 22, 42, 98, 77, 22, 25],
        [ 4, 17, 43, 89, 54, 89,  9, 35],
        [99, 32, 67, 86, 87, 30,  1, 52],
        [11, 58, 60, 79, 25, 54, 27, 63],
        [11, 65, 52, 25, 62, 89, 22,  7]],

       [[33, 10, 65, 92, 12, 80, 36, 70],
        [90,  6, 75, 80, 64, 83, 57, 98],
        [21, 37, 11, 23, 17, 96,  6, 73],
        [81, 66, 19, 94, 99, 90, 62,  8],
        [ 0, 

In [52]:
tf.gather(x,[2,4],axis=2) # 第3，5科目的成绩 

<tf.Tensor: id=253, shape=(4, 35, 2), dtype=int32, numpy=
array([[[78, 67],
        [62, 88],
        [40, 35],
        [49, 42],
        [59, 61],
        [17,  1],
        [76, 99],
        [28,  4],
        [91, 65],
        [69, 19],
        [39, 73],
        [13, 73],
        [88, 31],
        [74, 82],
        [37, 10],
        [25, 91],
        [ 4, 52],
        [67, 86],
        [26,  2],
        [63, 70],
        [ 1, 63],
        [55, 45],
        [ 3, 45],
        [95, 53],
        [42, 87],
        [38, 89],
        [ 0, 32],
        [ 9, 90],
        [58, 74],
        [ 0, 79],
        [11, 53],
        [19, 69],
        [96, 15],
        [75, 16],
        [23,  7]],

       [[33, 54],
        [78, 92],
        [ 9, 52],
        [78, 73],
        [83, 81],
        [65, 38],
        [ 9, 70],
        [73,  1],
        [40, 39],
        [21, 94],
        [51, 50],
        [79, 39],
        [27, 27],
        [19, 76],
        [ 9, 17],
        [55, 31],
        [66, 28],
    

In [53]:
# 根据多维坐标收集数据 
tf.gather_nd(x,[[1,1],[2,2],[3,3]]) 


<tf.Tensor: id=255, shape=(3, 8), dtype=int32, numpy=
array([[37, 89, 78,  1, 92, 50, 88, 33],
       [25, 58, 18, 93, 74, 14, 41, 87],
       [90,  6, 75, 80, 64, 83, 57, 98]])>

In [54]:
# 根据掩码方式采样科目 
tf.boolean_mask(x,mask=[True,False,False,True,True,False,False,True],axis=2) 

<tf.Tensor: id=283, shape=(4, 35, 4), dtype=int32, numpy=
array([[[39, 29, 67, 36],
        [88, 23, 88, 27],
        [55, 26, 35, 86],
        [57, 67, 42, 98],
        [23, 40, 61, 10],
        [90, 59,  1, 27],
        [39, 81, 99, 10],
        [40,  8,  4, 86],
        [99, 40, 65, 70],
        [16, 34, 19, 40],
        [58, 57, 73,  1],
        [16, 75, 73, 24],
        [41, 97, 31, 93],
        [65, 45, 82, 32],
        [98, 62, 10, 65],
        [50, 75, 91, 37],
        [69, 77, 52, 48],
        [ 4, 23, 86, 58],
        [39, 16,  2, 86],
        [94, 55, 70, 11],
        [56, 74, 63, 71],
        [99, 83, 45,  0],
        [63, 33, 45, 76],
        [95, 62, 53, 74],
        [71, 19, 87, 11],
        [45, 16, 89, 32],
        [63, 99, 32, 80],
        [74, 56, 90, 79],
        [94, 12, 74, 92],
        [29, 76, 79, 73],
        [46, 62, 53, 35],
        [88, 56, 69, 75],
        [95, 65, 15, 71],
        [24, 64, 16, 25],
        [73,  6,  7, 80]],

       [[43, 43, 54, 29],
    

In [55]:
 # 构造需要刷新数据的位置参数，即为4、3、1和7号位置 
indices = tf.constant([[4], [3], [1], [7]]) 
# 构造需要写入的数据，4号位写入4.4,3号位写入3.3，以此类推 
updates = tf.constant([4.4, 3.3, 1.1, 7.7])  
# 在长度为8的全0向量上根据indices写入updates数据 
tf.scatter_nd(indices, updates, [8]) 

<tf.Tensor: id=287, shape=(8,), dtype=float32, numpy=array([0. , 1.1, 0. , 3.3, 4.4, 0. , 0. , 7.7], dtype=float32)>